version: '3.8'
services:
  db:
    container_name: db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:5432
    networks:
      - main-network

  server:
    container_name: server
    build: .
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      - db
    networks:
      - main-network
    command: sh -c "npm run migration:up ; npm run seed:run ; npm start"

networks:
  main-network:
    driver: bridge

